openapi: 3.0.0
info:
  title: 자원 API
  version: 1.0.0
paths:
  /api/v1/storage:
    get:
      summary: 모든 자원 정보 조회
      description: Returns a list of resource objects.
      parameters:
        - name: factoryId
          in: query
          description: 공장ID
          required: false
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Stock'
components:
  schemas:
    Origin:
      type: object
      properties:
        id:
          type: integer
          format: int64
          description: Unique identifier
          default: 0
        name:
          type: string
          description: Origin name
          default: 0
        price:
          type: integer
          format: int64
          description: Origin price
          default: 0
    Stock:
      type: object
      properties:
        id:
          type: integer
          format: int64
          description: Unique identifier
          default: 0
        count:
          type: integer
          format: int64
          description: Total count of resources
          default: 0
        factoryId:
          type: integer
          format: int64
          description: ID of the owning factory
          default: 0
        Origin:
          $ref: '#/components/schemas/Origin'