server:
  port: 8081
  servlet:
    context-path: /

spring:
  kafka:
    topic: "test"
    consumer:
      group-id: "test"
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.use.type.headers: false
        spring.json.value.default.type: spring.storage.stock.StockConsumeDto
    properties:
      spring.json.trusted.packages: '*'
    bootstrap-servers: localhost:29092
  r2dbc:
    url: r2dbc:mysql://localhost:3306/tb01
    username: root
    pool:
      max-size: 10
      initial-size: 5

springdoc:
  api-docs:
    version: openapi_3_1
  swagger-ui:
    path: /v3/api-docs
    urls:
      - name: "자원 관리"
        url: /openapi/stock-spec.yaml
      - name: "원자제 관리"
        url: /openapi/origin-spec.yaml