server:
  port: 8081
  servlet:
    context-path: /

logging:
  level:
    io:
      r2dbc: DEBUG

spring:
  r2dbc:
    url: r2dbc:mysql://localhost:3306/tb01
    username: root
    pool:
      max-size: 10
      initial-size: 5

springdoc:
  api-docs:
    version: openapi_3_1
  swagger-ui:
    path: /v3/api-docs
    urls:
      - name: "자원 관리"
        url: /openapi/stock-spec.yaml
      - name: "원자제 관리"
        url: /openapi/origin-spec.yaml