apiVersion: v1
kind: Service
metadata:
  name: storage-service
  namespace: app
spec:
  selector:
    app: storage
  ports:
    - port: 80
      targetPort: 8081
      nodePort: 30081
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: storage
  namespace: app
  labels:
    app: storage
spec:
  replicas: 1
  selector:
    matchLabels:
      app: storage
  template:
    metadata:
      labels:
        app: storage
    spec:
      containers:
        - name: storage
          image: yooase12/kafka-project:storage
          ports:
            - containerPort: 8081
          envFrom:
            - secretRef:
                name: db-secret
            - configMapRef:
                name: webclient-config